"""Faction storylines data for LOGDTW2002

This file contains all faction storyline definitions. To add new factions or expand
existing ones, edit the FACTION_STORIES dictionary below.
"""

from typing import Dict
from game.story_types import FactionStoryline


# Complete faction storylines with detailed progression
FACTION_STORIES: Dict[str, FactionStoryline] = {
    "Federation": FactionStoryline(
        faction="Federation",
        summary="The Federation represents order, justice, and the protection of core worlds. As a Federation ally, you work to maintain peace, secure trade routes, and investigate threats to civilization.",
        missions=[
            "Secure Trade Routes",
            "Investigate Anomalies",
            "Patrol Core Sectors",
            "Rescue Stranded Vessels",
            "Eliminate Pirate Threats",
            "Establish Diplomatic Relations",
            "Protect Federation Assets",
            "Investigate Alien Artifacts",
        ],
        objectives=[
            "Maintain peace in core sectors",
            "Protect Federation trade convoys",
            "Investigate mysterious signals from deep space",
            "Establish contact with unknown alien species",
            "Prevent Genesis Torpedo technology from falling into wrong hands",
        ],
        progression_stages=[
            "Recruit: Basic patrol and escort missions",
            "Ensign: Investigate anomalies and rescue operations",
            "Lieutenant: Combat missions against pirates and threats",
            "Commander: Diplomatic missions and classified operations",
            "Captain: Lead major campaigns and access classified intel",
        ],
    ),
    "Pirates": FactionStoryline(
        faction="Pirates",
        summary="Pirates operate outside Federation law, ruling the outskirts through fear, profit, and cunning. As a pirate, you raid convoys, smuggle goods, and build a reputation for ruthlessness.",
        missions=[
            "Raid Convoys",
            "Smuggle Goods",
            "Establish Hideouts",
            "Recruit Crew Members",
            "Eliminate Rivals",
            "Secure Black Market Routes",
            "Steal Advanced Technology",
            "Build Pirate Fleet",
        ],
        objectives=[
            "Establish dominance in outer sectors",
            "Build a network of smuggling routes",
            "Acquire advanced weapons and technology",
            "Eliminate competing pirate factions",
            "Discover hidden Federation secrets",
        ],
        progression_stages=[
            "Rookie: Small raids and smuggling runs",
            "Raider: Organized convoy attacks",
            "Captain: Lead pirate crews and establish hideouts",
            "Warlord: Control sectors and eliminate rivals",
            "Pirate King: Command fleets and challenge Federation",
        ],
    ),
    "Scientists": FactionStoryline(
        faction="Scientists",
        summary="The Scientific Alliance pursues knowledge above all else. As a scientist, you explore the unknown, research alien technology, and push the boundaries of understanding.",
        missions=[
            "Explore Unknown Sectors",
            "Research Alien Technology",
            "Collect Specimens",
            "Analyze Anomalies",
            "Establish Research Stations",
            "Decode Ancient Artifacts",
            "Study Genesis Torpedo Technology",
            "Contact Alien Species",
        ],
        objectives=[
            "Discover the origins of Genesis Torpedo technology",
            "Map unexplored sectors and document findings",
            "Establish communication with alien civilizations",
            "Understand the true nature of the void",
            "Develop new technologies from alien artifacts",
        ],
        progression_stages=[
            "Researcher: Basic data collection and analysis",
            "Field Scientist: Explore dangerous sectors",
            "Senior Researcher: Lead research teams",
            "Chief Scientist: Access classified research",
            "Master Scientist: Pioneer breakthrough discoveries",
        ],
    ),
    "Traders": FactionStoryline(
        faction="Traders",
        summary="The Trader's Guild values profit, connections, and market dominance. As a trader, you build commercial empires, establish trade routes, and navigate complex economic systems.",
        missions=[
            "Establish Trade Routes",
            "Negotiate Contracts",
            "Expand Market Presence",
            "Acquire Rare Goods",
            "Build Trading Networks",
            "Invest in Markets",
            "Secure Exclusive Deals",
            "Dominate Sectors Economically",
        ],
        objectives=[
            "Build the largest trading network in the galaxy",
            "Control key trade routes and resources",
            "Establish exclusive contracts with major factions",
            "Profit from market fluctuations and opportunities",
            "Create economic dependencies that give you power",
        ],
        progression_stages=[
            "Merchant: Basic trading and small deals",
            "Trader: Establish routes and build reputation",
            "Merchant Prince: Control multiple sectors",
            "Trade Baron: Influence galactic markets",
            "Economic Overlord: Shape the galactic economy",
        ],
    ),
    "Neutral": FactionStoryline(
        faction="Neutral",
        summary="Independent operators who remain unaligned with major factions. As a neutral party, you maintain flexibility, work with whoever pays, and avoid the politics of larger powers.",
        missions=[
            "Freelance Operations",
            "Mediate Disputes",
            "Work for Multiple Factions",
            "Maintain Independence",
            "Exploit Faction Conflicts",
            "Build Personal Reputation",
            "Acquire Information",
            "Remain Unaligned",
        ],
        objectives=[
            "Maintain positive relations with all factions",
            "Profit from faction conflicts without taking sides",
            "Build a reputation as a reliable independent operator",
            "Acquire information and resources from all sources",
            "Remain free from faction obligations",
        ],
        progression_stages=[
            "Freelancer: Take jobs from anyone",
            "Independent Operator: Build reputation across factions",
            "Neutral Broker: Mediate between factions",
            "Master of None: Maintain perfect neutrality",
            "Free Agent: Command respect from all factions",
        ],
    ),
    "Empire": FactionStoryline(
        faction="Empire",
        summary="A militaristic faction that broke away from the Federation, seeking to establish order through strength and conquest. The Empire values discipline, hierarchy, and expansion.",
        missions=[
            "Conquer New Territories",
            "Establish Military Outposts",
            "Recruit Soldiers",
            "Eliminate Resistance",
            "Secure Resources",
            "Build War Machines",
            "Conduct Espionage",
            "Expand Borders",
        ],
        objectives=[
            "Establish the Empire as the dominant power",
            "Conquer key strategic sectors",
            "Build the largest military fleet",
            "Eliminate all opposition",
            "Create a new galactic order under Imperial rule",
        ],
        progression_stages=[
            "Recruit: Basic military training and patrols",
            "Soldier: Participate in conquest missions",
            "Officer: Lead small military units",
            "Commander: Command fleets and outposts",
            "General: Shape Imperial strategy and expansion",
        ],
    ),
    "Mercenaries": FactionStoryline(
        faction="Mercenaries",
        summary="Professional soldiers for hire who work for the highest bidder. Mercenaries value contracts, honor, and combat prowess above all else.",
        missions=[
            "Accept Contracts",
            "Complete Assassinations",
            "Protect Clients",
            "Raid Enemy Bases",
            "Escort Valuable Cargo",
            "Train Militias",
            "Collect Bounties",
            "Fight in Arena Battles",
        ],
        objectives=[
            "Build the most respected mercenary company",
            "Complete the most dangerous contracts",
            "Maintain perfect contract completion rate",
            "Establish reputation as the best fighters",
            "Accumulate wealth through successful missions",
        ],
        progression_stages=[
            "Rookie: Take simple protection jobs",
            "Veteran: Handle dangerous contracts",
            "Elite: Lead mercenary teams",
            "Legend: Command respect across all factions",
            "Master: Become the most sought-after mercenary",
        ],
    ),
    "Explorers": FactionStoryline(
        faction="Explorers",
        summary="Independent explorers who chart unknown space, discover new worlds, and seek adventure beyond the frontier. Explorers value discovery, freedom, and the unknown.",
        missions=[
            "Chart Unknown Sectors",
            "Discover New Planets",
            "Document Alien Life",
            "Map Anomalies",
            "Establish Outposts",
            "Collect Artifacts",
            "Study Phenomena",
            "Share Discoveries",
        ],
        objectives=[
            "Map the largest area of unexplored space",
            "Discover the most valuable resources",
            "Document new alien species",
            "Establish the first contact protocols",
            "Become the most renowned explorer in the galaxy",
        ],
        progression_stages=[
            "Scout: Explore nearby unknown sectors",
            "Explorer: Venture into dangerous regions",
            "Pioneer: Lead exploration expeditions",
            "Master Explorer: Discover legendary locations",
            "Galactic Cartographer: Map the entire galaxy",
        ],
    ),
    "Rebels": FactionStoryline(
        faction="Rebels",
        summary="Freedom fighters who oppose Federation control and fight for independence. Rebels value liberty, justice, and the right to self-determination.",
        missions=[
            "Sabotage Federation Operations",
            "Liberate Colonies",
            "Recruit Sympathizers",
            "Steal Supplies",
            "Disrupt Trade Routes",
            "Spread Propaganda",
            "Rescue Prisoners",
            "Build Resistance Network",
        ],
        objectives=[
            "Free colonies from Federation control",
            "Build a network of resistance cells",
            "Expose Federation corruption",
            "Gain support from neutral factions",
            "Establish independent government",
        ],
        progression_stages=[
            "Sympathizer: Support rebel operations secretly",
            "Fighter: Participate in rebel missions",
            "Leader: Organize rebel cells",
            "Commander: Coordinate major operations",
            "Revolutionary: Lead the fight for independence",
        ],
    ),
}

